### ISSUE TITLE
某些桌面环境不能显示托盘图标（或其它主题图标）

### ISSUE THREAD

**Issue by swordfeng** [Xinkai/XwareDesktop#110]
命令行输出：
[swordfeng@swordfeng-PC ~]% xware-desktop
QSystemTrayIcon::setVisible: No Icon set

托盘图标空白

system：archlinux
de：cinnamon
xware-desktop从AUR安装

**Comment by daya-prac** [comment]
Cinnamon没有托盘图标感觉怪怪的，有没有什么其它的解决方案？
