### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by dengdairiluo** [Xinkai/XwareDesktop#154]
发行版: Ubuntu 14.04.1 LTS 14.04
桌面环境: Unity/ubuntu
应用程序版本: 开发版

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/legacy/frontendpy.py", line 184, in log
    print("")
OSError: [Errno 5] 输入/输出错误
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
与 #79, #51 一样。
原因是什么我也不知道，猜测是Ubuntu带的Python的问题。
这个问题不会每次出现，所以只能忍着了。
