### ISSUE TITLE
与 Mate 桌面环境不兼容

### ISSUE THREAD

**Issue by xuzhuoyi** [Xinkai/XwareDesktop#161]
发行版: Ubuntu 14.04.1 LTS 14.04
桌面环境: mate
应用程序版本: ff12c6c520565a8d0eff1f96777a00fe3e57bd04

补充描述计算机。
Intel i7 CPU 4G RAM

简述在什么情况下发生了这个问题。
手动编译打包安装后首次启动即出错。

最近比较忙没时间研究，错误有可能出在与 Mate 桌面环境不兼容。有空我尝试解决一下。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 90, in __init__
    self.systray = Systray(self)
  File "/opt/xware-desktop/frontend/Widgets/systray.py", line 19, in __init__
    self.setIcon(icon)
  File "/opt/xware-desktop/frontend/Widgets/_KdeSystemTrayIcon.py", line 485, in setIcon
    raise ValueError("only support theme icon.")
ValueError: only support theme icon.
```
======================== 结束 ========================

**Comment by xuzhuoyi** [comment]
我看了一下，是 Mate 自带的主题图标与 Qt 不兼容所致。但只是图标无法显示，没有必要直接让整个程序中断。这里可以把抛出错误换成弹出 QMessageBox::warning 提示错误。这样也不至于有些桌面环境不能使用这个软件。

**Comment by Xinkai** [comment]
我没能merge你的改动，原因如下。

在KDE5、Unity这两个DE上旧的XEmbed标准的图标显示不出来，需要用新的方法。很多其它的程序都是用libappindicator来解决这一问题；而我是通过自己写的`Widgets/_KdeSystemIcon.py`这个文件来做的，原因是：Canonical的libappindicator不支持鼠标单击图标的动作。

据我所知，Mate、Cinnamon用的还是XEmbed标准的方式，所以`_KdeSystemIcon.py`这个文件按理说在Mate上就不应该被加载。

我刚刚在Arch上试了在Mate上运行，托盘图标不正常（本来应该是一个正方形的被压缩成了一个很窄的竖缝），但也没有出现你说的崩溃的情况。

不排除Ubuntu Mate版提供的Mate不是原版的Mate，所以上面我在Arch上的试验也就不做数了。但即便如此，你提出的改动方法也不是理想的。

**Comment by Xinkai** [comment]
与 #135 类似。

**Comment by Xinkai** [comment]
我想出一个办法，push到ThemeIcon这个branch了。
你试试吧。

**Comment by xuzhuoyi** [comment]
我试了一下。发现图标可以正确显示，而且也没有提示错误。但是有一个更严重的错误，菜单栏不见了。这样就无法设置 Xwared 托管等选项。下面是截图：
![screenshot](https://cloud.githubusercontent.com/assets/8327830/5891800/1333bc3a-a4e2-11e4-94b0-d94ba4b22607.png)

**Comment by Xinkai** [comment]
这个是Ubuntu的老毛病了，你需要把appmenu-qt5卸载掉。和这个问题无关。
关闭此问题。
