### ISSUE TITLE
'AdapterMap' object has no attribute 'get'

### ISSUE THREAD

**Issue by htfy96** [Xinkai/XwareDesktop#163]
发行版: Ubuntu 14.10 14.10 64bit
桌面环境: GNOME/gnome
应用程序版本: 7f4a4614f60d8fce015601422b2b55318f6a081d

简述在什么情况下发生了这个问题。
下载完成.tar文件，点击打开

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/Notify/_DBusNotifier.py", line 104, in slotActionInvoked
    taskItem = self.__taskModel.adapterMap.get(taskId, None)
AttributeError: 'AdapterMap' object has no attribute 'get'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
现在应该好了。修复在master里。
