### ISSUE TITLE
debian版本编译希望clean里面增加删除debian/下编译文件

### ISSUE THREAD

**Issue by wzhy90** [Xinkai/XwareDesktop#165]
在clean里面添加git clean -x -d -f debian/就可以了，rpm系的不清楚

**Comment by Xinkai** [comment]
这样做好处是什么？

**Comment by wzhy90** [comment]
清理debian编译后残留的东西

**Comment by Xinkai** [comment]
make clean就可以清理debian/下的东西，为什么要这个？即使不清理，下次编译的时候也会自动清理的吧？而且也不会被git收录。
