### ISSUE TITLE
OPENSUSE13.2编译错误

### ISSUE THREAD

**Issue by Millulu** [Xinkai/XwareDesktop#166]
/XwareDesktop/src/frontend/Extensions/src 中的DBusTypes.cpp
DBusTypes.cpp:7:36: error: ‘UnknownType’ is not a member of ‘QMetaType’
 int DBusTypes::GroupPropertyType = QMetaType::UnknownType;
                                    ^
DBusTypes.cpp: In static member function ‘static int DBusTypes::registerGroupProperty()’:
DBusTypes.cpp:10:30: error: ‘UnknownType’ is not a member of ‘QMetaType’
     if (GroupPropertyType == QMetaType::UnknownType) {
                              ^
它说UnknownType不属于QMetaType 
这是什么问题啊

**Comment by Millulu** [comment]
但是我自己看http://doc.qt.io/qt-5/qmetatype.html#Type-enum 上有QMetaType::UnknownType
而我也是安装的QT5啊

**Comment by Xinkai** [comment]
你看看 #132

**Comment by Xinkai** [comment]
我建议用rpm/里面的spec文件进行编译，不要make、make install。
不过这个文件是针对fedora做的，opensuse的话要不要修改我也不太清楚，我不太懂opensuse。
如果需要针对spec文件做opensuse的修改，我接受pr。
