### ISSUE TITLE
亲，为什么启动xware-desktop左下角三个都是红框？

### ISSUE THREAD

**Issue by hnuzhoulin** [Xinkai/XwareDesktop#169]
按照你的wiki里面的方法都试过了，重启过电脑，都一样.....提示没有绑定
没有xware相关进程

然后今天试了一下pointdownload的xware插件，可以绑定，可以起EmbedThunderManager进程，这个时候再起xware-desktop可以下载，显示下载器在线，但是左下角的三个还是红色.....

**Comment by Xinkai** [comment]
pointdownload和本项目使用的不是同一份profile，两个独立的互相看不见。
本软件的EmbedThunderManager要通过/opt/xware-desktop/xwared执行。（可能与pointdownload带的xware端口冲突所以需要关掉一个。。）

**Comment by Xinkai** [comment]
仅是“据我所知”，对PointDownload的没做太深入研究。。

**Comment by hnuzhoulin** [comment]
我现在已经卸载pointDownload
现在启动xware不会自己启动/opt/xware-desktop/xwared，手动执行后可以正常下载....

**Comment by Xinkai** [comment]
文件，设置里有自动起动选项
