### ISSUE TITLE
firefox的插件flashgot打不开xware客户端

### ISSUE THREAD

**Issue by Jeajone** [Xinkai/XwareDesktop#170]
按照方法设置了名称为xware-desktop，参数设置默认为[URL]的新的下载器，路径没错 为/usr/share/applications/xware-desktop.desktop 但是每次点flashgot都没有反应，不会启动程序弹出新建任务框，只有复制迅雷链接时才会自动新建任务

**Comment by Xinkai** [comment]
路径应设为`/usr/bin/xware-desktop`
