### ISSUE TITLE
下一代的desktop进展如何了？

### ISSUE THREAD

**Issue by xsjqqq123** [Xinkai/XwareDesktop#171]
由于用这个网页版本的不方便，最近开始研究了下xware固件，本打算自己按想法写一个的，但无意中在wiki见到有下一代的desktop计划，请问它进行得怎样了？
目前我找到的本地方法：
得到设备key或信息:http://127.0.0.1:9000/getsysinfo
解绑：http://127.0.0.1:9000/unbind
绑定：http://127.0.0.1:9000/bind   这个参数不懂怎样。
其它的您都知道吗？是否可以直接操纵具有下载功能的那个二进制文件？ETMDaemon是什么啊？

**Comment by Xinkai** [comment]
QML界面现在没在做。xware的本地接口的bug很多，现在即使做出来也不好使。Aria的接口也有挺多别扭的地方，要做的话还要先改Aria2。
ETMDaemon是迅雷官方的daemon，我也不知道怎么用。虽然安装了，但是没用到。portal也是一样的。
