### ISSUE TITLE
！！迅雷后台更新维护，近期无法使用！！

### ISSUE THREAD

**Issue by ziyang3721** [Xinkai/XwareDesktop#175]
不知道我的是不是特例但还是提醒下，我参考该网页换成 1.0.16 版本可以使用。

http://g.xunlei.com/thread-14806-1-1.html

感谢原作者的作品.

**Comment by Xinkai** [comment]
感谢反馈。
出现这种现象有可能是xware要出3了吗？也有可能是迅雷要放弃这个项目了。
无论是哪个，换回旧版都是不彻底的解决方法。大家急着用的可以暂时换回去。我这次就先标记为wontfix了，再等一下有没有什么新消息。

**Comment by MidoriYakumo** [comment]
左下角绿红红也是这个原因吗?

**Comment by Xinkai** [comment]
对

**Comment by xiaomotou** [comment]
Xware1.0.31已恢复正常使用
http://g.xunlei.com/thread-14828-1-1.html

**Comment by Xinkai** [comment]
嗯，好。
