### ISSUE TITLE
运行登录后无法激活设备,停留在"没有可用控制远程的设备"页面

### ISSUE THREAD

**Issue by blurm** [Xinkai/XwareDesktop#176]
今天在ubuntu14.04 lts安装了一下,按照git上的使用说明. 登录之后提示"亲, 你还没有可用控制远程的设备哦~"

左下角的xwared显示绿色对勾
但是ETM 和web前端显示橙色叹号
ETM提示设备未激活

按作者之前帖子里的方法试了下也无效:

要是以前能用的话，说不定是迅雷服务器暂时故障，可以稍等一下。
如果过了一段时间还是不行，你可以这样试一下。
1. 在后端菜单选择停止。
2. 到~/.xware-desktop/profile，把cfg文件夹改个名字。
3. 在后端菜单选择开始。
4. 在文件菜单选择刷新页面。
这样会重置ETM的配置文件，设置归零。（重装软件包只是对重装程序文件，配置文件不变。）如此一来应该重新激活。
要是此法成功，你可以到所有设备里，删除之前的那个激活的设备项。
![screenshot from 2015-03-25 21 52 23](https://cloud.githubusercontent.com/assets/10203631/6826214/c75477d2-d33a-11e4-85b7-7c99956dc52d.png)

**Comment by Xinkai** [comment]
见 #175。
