### ISSUE TITLE
切换用户登录提示"登录的迅雷账户不是绑定的迅雷账户",无法解绑定

### ISSUE THREAD

**Issue by blurm** [Xinkai/XwareDesktop#177]
使用临时账户登录并使用. 临时账户过期之后, 使用另外的账户无法登录到UI里解绑定

**Comment by Xinkai** [comment]
关闭xwared，清空/home/xinkai/.xware-desktop/profile/cfg的所有内容，然后再试。

**Comment by blurm** [comment]
是否需要把所有相关进程终止掉再删除? 删除cfg下所有内容登录时还是记录有账户自动进去了,不过又试了一次重启之后稀里糊涂进去了:)

**Comment by Xinkai** [comment]
那就好
