### ISSUE TITLE
embedthunderManager 进程高cpu

### ISSUE THREAD

**Issue by iampkuhz** [Xinkai/XwareDesktop#179]
我在下载的时候embedthunderManager进程占用单核cpu达到100%，风扇响的厉害，有什么方法降低cpu使用率吗？
我的笔记本cpu： i7 4550u
环境 ubuntu14.04 64 bit

**Comment by Xinkai** [comment]
这个问题去找迅雷官方才有可能解决

**Comment by iampkuhz** [comment]
好的，谢谢
