### ISSUE TITLE
Xware desktop对cpu有没有要求

### ISSUE THREAD

**Issue by TigerSnake** [Xinkai/XwareDesktop#181]
我在amd的平台上安装后总是不能自动激活，ETM和web前端都没有变绿，但是在intel的笔记本上安装就没有问题，想请问一下，会不会对cpu有什么要求?

**Comment by Xinkai** [comment]
没问题的

**Comment by Xinkai** [comment]
你之前不能激活与cpu无关。可能迅雷服务器不稳定
