### ISSUE TITLE
ETM和web前端显示红色，登录后没有提示绑定设备，请问下是不是迅雷那边又关闭了服务？

### ISSUE THREAD

**Issue by blurm** [Xinkai/XwareDesktop#183]
如题，因为登录后发现提示设备断开，所以卸载重装了xwared

之后就如题提示，又无法绑定设备了

**Comment by Xinkai** [comment]
他们服务器经常不灵的。

卸载重装本软件，只要不动~/.xware-desktop  绑定就还在。
