### ISSUE TITLE
一直在解析下载连接

### ISSUE THREAD

**Issue by evanchicken** [Xinkai/XwareDesktop#184]
无论是FTP的下载地址还是BT种子，都是一直提示正在解析下载地址或者是正在解析BT种子，无法执行下载命令。（Ubuntu 14.04，自己按照说明编译的deb包）

**Comment by Xinkai** [comment]
大概是下载核心问题或服务器问题

**Comment by joyoki** [comment]
该问题一般出现在墙外种子或者网络不畅的资源上，初步定位网络问题或者服务器问题
