### ISSUE TITLE
ETM和web前段一直显示红色

### ISSUE THREAD

**Issue by ShijieLi** [Xinkai/XwareDesktop#185]
安装之后就按照使用说明一步步的来，xwared开启了，可是ETM和web前段一直是红色
按照故障排查中的方法也没有用
![20150427150148](https://cloud.githubusercontent.com/assets/866777/7343020/add39612-ecee-11e4-9bc4-de86478e6576.png)

**Comment by Xinkai** [comment]
鼠标移到ETM上有什么？

**Comment by ShijieLi** [comment]
移到ETM上显示
“ETM运行中 设备未激活”
移到Web前段显示
“页面代码已插入 设备已登陆 设备在线”

**Comment by blurm** [comment]
相同的问题, 重新安装了之后就一直提示没有可用控制远程的设备

**Comment by Xinkai** [comment]
尝试把~/.xware-desktop文件夹改个名字，可以重置所有设置。也需要重新挂载。
如果不行，再把这个文件夹名字改回来

**Comment by ShijieLi** [comment]
没有用，问题依旧

**Comment by tzpgla** [comment]
出现过同样的问题，解决方法是
1、解除绑定 后 重新绑定   如果仍未生效 则重装 
2、取消会员功能中的 离线 和 高速
3、删除所有 正在下载 的任务 再次下载的时候  任务不超过2个

**Comment by blurm** [comment]
依然不行啊, 请问这是普遍问题还是个别问题啊

**Comment by Xinkai** [comment]
比较普遍……这个恐怕是迅雷二进制的问题，或者是你的网络的问题。
哎，要用个下载软件还必须要验证用户，太坑。

**Comment by Xinkai** [comment]
清理长期无进展问题
