### ISSUE TITLE
关闭之后报的错误信息

### ISSUE THREAD

**Issue by danifer1018** [Xinkai/XwareDesktop#186]
发行版: Ubuntu 14.04.2 LTS 14.04
桌面环境: Unity/ubuntu
应用程序版本: 0c693745567dc5e831f1c99ccd6edc7d386f1db1

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/legacy/frontendpy.py", line 184, in log
    print("")
OSError: [Errno 5] 输入/输出错误
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
Ubuntu的老毛病了。好在不经常犯，只能忍了。
