### ISSUE TITLE
打包编译出错

### ISSUE THREAD

**Issue by jhkwei** [Xinkai/XwareDesktop#187]
find /home/shenwei/test/XwareDesktop/debian/xware-desktop -type f -print0 | xargs -0 chmod 644
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
find /home/shenwei/test/XwareDesktop/debian/xware-desktop -type d -print0 | xargs -0 chmod 755
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
# mark executables
chmod +x /home/shenwei/test/XwareDesktop/debian/xware-desktop/opt/xware-desktop/frontend/launcher.py
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
chmod +x /home/shenwei/test/XwareDesktop/debian/xware-desktop/opt/xware-desktop/frontend/morula.py
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
chmod +x /home/shenwei/test/XwareDesktop/debian/xware-desktop/opt/xware-desktop/frontend/CrashReport/CrashReportApp.py
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
chmod +x /home/shenwei/test/XwareDesktop/debian/xware-desktop/opt/xware-desktop/daemon/xwared.py
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
chmod +x /home/shenwei/test/XwareDesktop/debian/xware-desktop/opt/xware-desktop/xware/lib/EmbedThunderManager
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
chmod +x /home/shenwei/test/XwareDesktop/debian/xware-desktop/opt/xware-desktop/xware/lib/ETMDaemon
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
chmod +x /home/shenwei/test/XwareDesktop/debian/xware-desktop/opt/xware-desktop/xware/lib/vod_httpserver
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
chmod +x /home/shenwei/test/XwareDesktop/debian/xware-desktop/opt/xware-desktop/xware/portal
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
chmod +x /home/shenwei/test/XwareDesktop/debian/xware-desktop/opt/xware-desktop/chmns
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
make[1]:正在离开目录 `/home/shenwei/test/XwareDesktop'
   dh_install
   dh_installdocs
	install -g 0 -o 0 -d debian/xware-desktop/usr/share/doc/xware-desktop
   dh_installchangelogs
	install -o 0 -g 0 -p -m644 debian/changelog debian/xware-desktop/usr/share/doc/xware-desktop/changelog
   dh_icons
   dh_perl
   dh_link
	rm -f debian/xware-desktop/usr/bin/xware-desktop
	ln -sf /opt/xware-desktop/frontend/launcher.py debian/xware-desktop/usr/bin/xware-desktop
	rm -f debian/xware-desktop/opt/xware-desktop/xwared
	ln -sf daemon/xwared.py debian/xware-desktop/opt/xware-desktop/xwared
   dh_compress
	cd debian/xware-desktop
	chmod a-x usr/share/doc/xware-desktop/changelog
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
	gzip -9nf usr/share/doc/xware-desktop/changelog
	cd '/home/shenwei/test/XwareDesktop'
   dh_fixperms
	find debian/xware-desktop  -print0 2>/dev/null | xargs -0r chown --no-dereference 0:0
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
	find debian/xware-desktop ! -type l  -print0 2>/dev/null | xargs -0r chmod go=rX,u+rw,a-s
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
	find debian/xware-desktop/usr/share/doc -type f  ! -regex 'debian/xware-desktop/usr/share/doc/[^/]*/examples/.*' -print0 2>/dev/null | xargs -0r chmod 644
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
	find debian/xware-desktop/usr/share/doc -type d  -print0 2>/dev/null | xargs -0r chmod 755
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
	find debian/xware-desktop/usr/share/man debian/xware-desktop/usr/man/ debian/xware-desktop/usr/X11*/man/ -type f  -print0 2>/dev/null | xargs -0r chmod 644
	find debian/xware-desktop -perm -5 -type f \( -name '*.so.*' -or -name '*.so' -or -name '*.la' -or -name '*.a' \)  -print0 2>/dev/null | xargs -0r chmod 644
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
	find debian/xware-desktop/usr/include -type f  -print0 2>/dev/null | xargs -0r chmod 644
	find debian/xware-desktop/usr/share/applications -type f  -print0 2>/dev/null | xargs -0r chmod 644
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
	find debian/xware-desktop -perm -5 -type f \( -name '*.cmxs' \)  -print0 2>/dev/null | xargs -0r chmod 644
	find debian/xware-desktop/usr/lib/perl5 debian/xware-desktop/usr/share/perl5 -type f -perm -5 -name '*.pm'  -print0 2>/dev/null | xargs -0r chmod a-X
	find debian/xware-desktop/usr/bin -type f  -print0 2>/dev/null | xargs -0r chmod a+x
	find debian/xware-desktop/usr/lib -type f -name '*.ali'  -print0 2>/dev/null | xargs -0r chmod uga-w
   dh_strip
	strip --remove-section=.comment --remove-section=.note --strip-unneeded debian/xware-desktop/opt/xware-desktop/etmpatch.so
strip:debian/xware-desktop/opt/xware-desktop/etmpatch.so: could not create temporary file to hold stripped copy: 无错误
dh_strip: strip --remove-section=.comment --remove-section=.note --strip-unneeded debian/xware-desktop/opt/xware-desktop/etmpatch.so returned exit code 1
make: *** [binary] 错误 29
dpkg-buildpackage: 错误: fakeroot debian/rules binary 提供错误退出状态 2

**Comment by Xinkai** [comment]
大概是你的编译环境问题。估计你是64位系统没有装64位的fakeroot吧。

**Comment by Xinkai** [comment]
应该是你没有设置了不安装recommends和suggests的包吧～前两天我也遇到了。
这个问题在 b1fa67871f63f86a864408ff5d96358cd1459b61 里修复了。

所以这个问题就关闭了。如果还有问题请重新打开。
