### ISSUE TITLE
xware etm web前段都显示红字

### ISSUE THREAD

**Issue by cjwddtc** [Xinkai/XwareDesktop#189]
我按照说明一步一步的编译安装，打开后无法找到文件->设置->挂载
只有一个登录截面其他什么都没有
![2015-05-27 17 16 52](https://cloud.githubusercontent.com/assets/6771700/7832784/31d68c14-0494-11e5-9053-5f7a76898cd6.png)
是否迅雷的xware要另外单独安装？如果要的话如何安装？

**Comment by Xinkai** [comment]
Unity有Bug，菜单显示不出来。
卸载掉`appmenu-qt5`。

**Comment by Xinkai** [comment]
卸载掉之后重启程序就可以了。不需要重启电脑～
