### ISSUE TITLE
mount分区可用容量错误

### ISSUE THREAD

**Issue by zhfreal** [Xinkai/XwareDesktop#190]
Ubuntu14.04下，将ntfs分区挂载到home一目录下，然后在xware-desktop中挂载该挂载点，登录正常激活。但界面上显示的NAS可用大小仍为home分区的可用大小，非ntfs分区的可用大小。

**Comment by Xinkai** [comment]
这个问题不好解决。
迅雷的二进制的做法，是以为每一个挂载路径都是一块物理设备。因为要拿到桌面电脑上用，我做了一些修改，给迅雷的二进制谎报了一些设备。
所以通过迅雷的界面上看到的大小都是不对的。比如你把~/Download和~/下载都挂载，迅雷检测到的大小实际上是/home的两倍。

**Comment by zhfreal** [comment]
我直接执行portal，运行后台并得到绑定码，然后在浏览器上登录远程下载并绑定设备，然后可以找到我正确的ntfs分区。此时是挂载在/media目录下。但是同样条件下，xware-desktop不行。

**Comment by Xinkai** [comment]
对。你直接运行会找到真实的外接物理设备，所以得到的结果是正确的。
而xware-desktop为了让xware可以下载到内置的硬盘上，会加载一个我写的补丁。这个补丁会把普通的文件夹伪装成设备。但是这样做的代价就是得到的设备信息（包括大小）是错的。

**Comment by Xinkai** [comment]
其实这个解决起来也不是绝对不可能。理论上，通过完善补丁应该可以消除这个副作用。但是这是个小问题，与做出的改动相比不值得。所以我不会做这个修改的。

再说我们可以期待一下内测中的xware3.0。说不定3.0就会自动支持下载到任意制定的位置，不管那个位置是真实的外置硬盘，还是内置硬盘。要是那样的话，这个问题就会自动解决了。

**Comment by zhfreal** [comment]
OK， 多谢

**Comment by zhfreal** [comment]
我或许想到了一个解决方法，可用解决下载到任意目录（外置，内置），并得到正确的容量。而且python代码实现可能更精简。

目前xware似乎只认/media下挂载的。对于外置来说，问题不大。对于内置来说，只要通过mount --bind方法，将已挂载的任意目录bind到/media下，xware就会认，而且容量大小之类的是正确的。我已经在xware-1.0.31上试过，其它版本未试。

这个问题实际上有现实意义。不少Linux用户的/home分区都不会太大，可用空间更不大。但离线下载的文件往往不小。比如，现在的一个蓝光原盘文件动不动就几十G。这可能已经超过了/home的可用空间。这种情况下，根本无法下载。

如果觉得可行，而且有时间，可以考虑下。

多谢

**Comment by Xinkai** [comment]
现在就是用mount bind的方法做挂载的。
https://github.com/Xinkai/XwareDesktop/blob/master/src/chmns.c

**Comment by Xinkai** [comment]
xware-desktop是利用拦截xware读取/proc/mount文件的方式，达到指定下载文件夹的。
https://github.com/Xinkai/XwareDesktop/blob/master/src/etmpatch.c#L85

mount bind的办法我知道。在chmns.c里面用了这个办法独立出/tmp。没有用它做挂载管理的原因是，它只能增加挂载，好像不能把真实的分区屏蔽掉。也就是说，如果用户插入U盘，xware会什么都不问就新建ThunderDB这个文件夹。所以没有采用这个方案，而是使用提供假的mount文件的办法。

至于为什么会造成磁盘大小检测错误的问题，可能因为xware-desktop对原版做的另外一个包装有关。
比如用户选择下载到~/Downloads，真实的下载路径其实在~/.xware-desktop/profile/mnt里面，通过软链接链接到~/Downloads。这么做是为了隐藏xware自己在每一个下载路径里创建TDDownload和ThunderDB文件夹。。。但是如此一来，挂载点的所在磁盘就成了/home的所在盘。

这个问题希望我解释得明白了。我还是不会处理这个问题。

就你的情况，你可以这样试一下，把真实的设备挂载到~/.xware-desktop/profile/mnt/?????，这样应该就可以解决这个问题。我没试过，也不确定。。

**Comment by zhfreal** [comment]
多谢关注。我直接用的xware + 浏览器。
就 xware自动增加目录 和 容量正确与否，个人觉得或许容量才是应该优先考虑的问题。容量是可能影响功能是否可用的因素，而自动增加目录/文件那也只是xware带来的额外烦恼，而不涉及主要功能。

站在一个产品人的角度，只是希望xware-desktop能越来越好。有冒犯之处还请谅解。
