### ISSUE TITLE
web error

### ISSUE THREAD

**Issue by joyoki** [Xinkai/XwareDesktop#192]
发行版: Ubuntu 14.04.2 LTS 14.04
桌面环境: Unity/gnome-fallback
应用程序版本: b1fa67871f63f86a864408ff5d96358cd1459b61

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 57, in __init__
    self.checkOneInstance()
  File "/usr/bin/xware-desktop", line 137, in checkOneInstance
    fd = os.open(constants.FRONTEND_LOCK, os.O_RDWR | os.O_CREAT)
FileNotFoundError: [Errno 2] No such file or directory: '/home/navis/.xware-desktop/profile/tmp/xware_frontend.lock'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
问题一直都有么？

**Comment by joyoki** [comment]
非常感谢回复,方便微信或者QQ详聊嘛? 我在ubuntu论坛反馈了 我的wechat ID: bainanshun

**Comment by Xinkai** [comment]
还是电脑键盘打字快。。你要有时间就在这里说吧。我今天晚上都可以聊的

**Comment by Xinkai** [comment]
其实我刚才的问题是问你，再启动一次会不会再次出现。。
因为看到这个错误就像是，在运行过程中，某些文件被删除了一样。

**Comment by joyoki** [comment]
抱歉，网络有点抽风。这个issue 出现一次以后，只要启动迅雷，就会一直出现，造成迅雷无法启动

**Comment by Xinkai** [comment]
你看看是不是`/home/navis/.xware-desktop/profile/tmp/`这个目录结构不完整。
执行下`mkdir -p /home/navis/.xware-desktop/profile/tmp`试试。

**Comment by joyoki** [comment]
好的 多谢,我现在就在ubuntu下, 我试后给你反馈

**Comment by Xinkai** [comment]
Ubuntu的bug。
解决办法是删掉`appmenu-qt5`。

**Comment by joyoki** [comment]
已经确认 确实是目录不完整造成的,执行 mkdir -p /home/navis/.xware-desktop/profile/tmp以后 错误消失, 同时卸载appmenu-qt5(电脑未重启)  还是没见到 "文件"设置等菜单 只有账号登陆和迅雷远程下载界面

**Comment by Xinkai** [comment]
下次重启后看看会不会显示吧。
以前好多人都遇到这个问题的。

**Comment by joyoki** [comment]
已经确认 确实是目录不完整造成的,执行 mkdir -p /home/navis/.xware-desktop/profile/tmp以后 错误消失, 同时卸载appmenu-qt5(电脑未重启)  可以看到 "文件"设置等菜单  多谢解决

**Comment by joyoki** [comment]
非常感谢 ,笔记mark一下
