### ISSUE TITLE
ubuntu14.04 64bit编译器是4.8的，看不懂编译说明里关于非4.9的内容

### ISSUE THREAD

**Issue by yuyuen72** [Xinkai/XwareDesktop#194]
gcc版本是4.8的，但是看不懂编译说明里关于非4.9的修改内容

**Comment by Xinkai** [comment]
其实我也没看懂，那段不是我加的。
跳过去试试看行不行。

Ubuntu14.04应该是不用任何改动直接编译成功的～

**Comment by yuyuen72** [comment]
@Xinkai ok，什么都没改，直接编译成功了
