### ISSUE TITLE
xware-desktop崩溃

### ISSUE THREAD

**Issue by alldnregret** [Xinkai/XwareDesktop#195]
发行版: Debian GNU/Linux 8 (jessie) 8
桌面环境: X-Cinnamon/lightdm-xsession
应用程序版本: b1fa67871f63f86a864408ff5d96358cd1459b61

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。
更改挂载点是出现错误，后面重新打开，点击菜单“文件”时也会出现同样的错误提示。原来unix挂载点设置为/media/thunder,但是实际的下载路径却是～/ThunderDownloads;然后吧unix挂载点设置为/media/cheng/bigone,点击确定后出现了如下错误。
======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/libxware/mounts.py", line 153, in getMountsMapping
    localPath = self._mounts[mntPath]
KeyError: '/home/cheng/.xware-desktop/profile/mnt/media\\thunder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/legacy/main.py", line 62, in slotSetting
    self.settingsDialog = SettingsDialog(self)
  File "/opt/xware-desktop/frontend/legacy/settings.py", line 86, in __init__
    self.setupMounts()
  File "/opt/xware-desktop/frontend/legacy/settings.py", line 104, in setupMounts
    mountsMapping = app.adapterManager[0].mountsFaker.getMountsMapping()
  File "/opt/xware-desktop/frontend/libxware/mounts.py", line 155, in getMountsMapping
    raise KeyError("触发问题#131。", drive, mntPath, self._mounts)
KeyError: ('触发问题#131。', 'P:', '/home/cheng/.xware-desktop/profile/mnt/media\\thunder', OrderedDict([('/home/cheng/.xware-desktop/profile/mnt/media\\cheng\\bigone', '/media/cheng/bigone')]))
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
如果一直出现这个问题，可以把`~/.xware-desktop/profile/etc/mounts`的内容贴一下，便于我分析原因。
贴完了可以删掉这个文件，这样能重置挂载设置。

**Comment by alldnregret** [comment]
不好意，当时的文件已经不在了。我重装了一次，重新配置挂在点，不崩溃，但是前端显示的磁盘容量使用36GB，而实际上是有100多的。再次添加原来导致崩溃的挂载点 /media/cheng/bigone，软件却能够正常运行。下面是mounts文件内容：
  1 # This file is automatically generated by Xware Desktop. Manually modifying     this file via a text editor is not advised.  2 /media/thunder /home/cheng/.xware-desktop/profile/mnt/media\thunder auto def    aults,rw 0 0  3 /media/cheng/bigone /home/cheng/.xware-desktop/profile/mnt/media\cheng\bigon    e auto defaults,rw 0 0   
今天早上看的时候 貌似 这样的：   2/media/cheng/bigone /home/cheng/.xware-desktop/profile/mnt/media\\cheng\\bigon    e auto defaults,rw 0 0                                                                                              
Date: Wed, 22 Jul 2015 03:33:02 -0700

**Comment by alldnregret** [comment]
关于容量的问题，网页版也显示不正确，磁盘格式为ext4（hdd），系统装在sdd上。

Date: Wed, 22 Jul 2015 03:33:02 -0700

**Comment by Xinkai** [comment]
你说的重装，包括删掉`~/.xware-desktop`吗？如果重装只是重新安装包的问题的话，那么`~/.xware-desktop/profile/etc/mounts`没有变化。
这个问题其实之前好多人都遇到过，只是我一直没想明白到底是怎么发生的。
所以在那个地方特别写明了，触发131  但好像也没有什么帮助。

好在这个问题即使不重装，再次启动好像就会自己消失。

关于空间大小问题，你可以看这个问题 #190。暂时不会修复的。

**Comment by Xinkai** [comment]
崩溃问题已经不再发生 关闭此问题
