### ISSUE TITLE
RuntimeError: the sip module implements API

### ISSUE THREAD

**Issue by daya-prac** [Xinkai/XwareDesktop#196]
发行版: Ubuntu 14.04.2 LTS 14.04
桌面环境: Unity/ubuntu
应用程序版本: b1fa67871f63f86a864408ff5d96358cd1459b61

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
安装后第一次启动。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 85, in __init__
    from Widgets.systray import Systray
  File "/opt/xware-desktop/frontend/Widgets/__init__.py", line 15, in <module>
    from ._KdeSystemTrayIcon import KdeSystemTrayIcon as CompatSystemTrayIcon
  File "/opt/xware-desktop/frontend/Widgets/_KdeSystemTrayIcon.py", line 12, in <module>
    from Extensions.DBusTypes import DBusTypes
RuntimeError: the sip module implements API v11.0 but the DBusTypes module requires API v11.1
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
你应该是安装了某个程序的PPA版本，它替换了系统的Qt
找到哪个程序使用了非官方源的Qt，然后卸载

**Comment by daya-prac** [comment]
我的电脑上除了WPS之外貌似也没有其它的程序使用QT了

**Comment by Xinkai** [comment]
我记得这个问题以前也有人提过。忘记最后解决了没有了。

**Comment by Xinkai** [comment]
#180 重复问题

**Comment by Xinkai** [comment]
执行下
```
apt-cache policy python3-sip-dev
```

贴结果

**Comment by daya-prac** [comment]
python3-sip-dev:
  已安装：  (无)
  候选软件包：4.15.5-1build1
  版本列表：
     4.15.5-1build1 0
        500 http://mirrors.ustc.edu.cn/ubuntu/ trusty/main amd64 Packages

**Comment by Xinkai** [comment]
请问还有这个问题么

**Comment by Matrix0xCC** [comment]
原因是sip的版本过低，需要手动下载源码编译安装。

1. 首先删除python3的dist-packages中的sip相关文件。
cd /usr/lib/python3/dist-packages
sudo rm sip*
2. 到 http://pyqt.sourceforge.net/Docs/sip4/installation.html 下载最新源码并解压。
python3 configure.py
make && make install
3. 此时dist-package下面就有了最新的sip动态库，程序应该可以运行了。
4. 检测版本
string sip.so | grep -e "[0-9][0-9.]\+"会显示版本号。该版本号应该和
python3 -c "import sip;print(sip.SIP_VERSION_STR)"的输出一致。
若不一致说明python3没有使用正确的sip库。
