### ISSUE TITLE
是否可以改变ETM的端口？

### ISSUE THREAD

**Issue by myme5261314** [Xinkai/XwareDesktop#199]
你好，我现在遇到一个问题，ETM开机启动会占用1080端口如下。
tcp        0      0 0.0.0.0:1080            0.0.0.0:*               LISTEN      15491/EmbedThunderM
因为本机开了代理程序端口是1080，因此会有冲突，请问是否有方法可以修改ETM的端口为1080以外的端口，如果有如何做，谢谢。
我的系统是Ubuntu 14.04。
当然是可以调整代理程序使用的端口，不过由于一些原因，这样做会导致一些麻烦，因此，还是向能够改变ETM的端口。

**Comment by myme5261314** [comment]
好吧，刚提完问题，自己就解决了。
解决方法如下：
在XwareDesktop的设置中
ETM何时启动设置为：随前端启动而启动，随前端退出而退出。
然后代理程序设置开机启动。
代理程序抢占了1080端口后，ETM启动时会自动使用别的端口。

**Comment by oyvfhp** [comment]
ETM可以改变端口的。
