### ISSUE TITLE
xware desktop have no ‘file’ ‘front-end’ menu options

### ISSUE THREAD

**Issue by JosephDhF** [Xinkai/XwareDesktop#200]
![Uploading 2015-08-07 11:02:37屏幕截图.png…]()

**Comment by JosephDhF** [comment]
![image](https://cloud.githubusercontent.com/assets/13658376/9127983/b9789cd2-3cf4-11e5-9ebb-3025d0badf42.png)

**Comment by Xinkai** [comment]
额..最下面的东西最有用 截图里没有

**Comment by JosephDhF** [comment]
哦，后来没有出现过了；至于没有菜单栏，是由于appmenu-qt5导致的，卸载之后就好了，如果能修复当然最好了，不过还是非常感谢的！

**Comment by Xinkai** [comment]
好的 那有问题再提
