### ISSUE TITLE
依赖正常，dpkg-buildpackage打包时出现如下错误

### ISSUE THREAD

**Issue by fsyxhua** [Xinkai/XwareDesktop#203]
fsyx@fsyx-Dell:XwareDesktop$ dpkg-buildpackage 
Error parsing time at /usr/lib/x86_64-linux-gnu/perl/5.20/Time/Piece.pm line 469, <$filehandle> line 5.

**Comment by Xinkai** [comment]
应该是系统问题吧

**Comment by Xinkai** [comment]
知道问题了。等我有空了修

**Comment by Xinkai** [comment]
拉下最新的代码再试试吧 应该好了
