### ISSUE TITLE
Xware Desktop 运行时出错

### ISSUE THREAD

**Issue by tasmilen** [Xinkai/XwareDesktop#204]
发行版: Ubuntu 14.04.3 LTS 14.04
桌面环境: 未知/xubuntu
应用程序版本: 823f232dbd6f64fadc42388ccb8bb3bad4404046

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 272, in QtMsgHandler
    file = sys.stdout if msgType in (QtDebugMsg, QtWarningMsg) else sys.stderr)
OSError: [Errno 5] Input/output error
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
Ubuntu的问题
