### ISSUE TITLE
默认启动 端口占用

### ISSUE THREAD

**Issue by DearMadMan** [Xinkai/XwareDesktop#209]
可以在哪里进行端口配置？
xware 默认启动占用 1080 和 9000端口
1080 与 shadowsocks 冲突
9000 与 php-fpm 端口冲突

**Comment by Xinkai** [comment]
声明 本人不支持更改端口启动 所以建议你改其它的软件。

不过其实是可以改的
`~/.xware-desktop/profile/cfg` 里面改xware相关的
还需要改`~/.xware-desktop/profile/etc/frontend.ini` 里面的。我记得我做了端口的设置了，不过默认是没出来的，你可以看看源码。

**Comment by zhenxxin** [comment]
多谢两位的提醒，我是把 ETM 改成了：随前端启动而启动，随前端退出而退出
这样浏览器的代理基本能解决了（先开 Shadowsocks， 后开 Xware 貌似也没冲突？）。
至于 php-fpm 可以改成用 unix sock 的形式跑！
