### ISSUE TITLE
xware-desktop bug

### ISSUE THREAD

**Issue by t8c** [Xinkai/XwareDesktop#211]
发行版: Fedora 22 (Twenty Two) 22
桌面环境: GNOME/gnome
应用程序版本: 开发版

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
现在每次启动xware程序都这样。

======================== 报告 ========================
错误发生在MainThread
```
TypeError: invalid result from TaskModel.roleNames(), a dict value has type 'str' but 'QByteArray' is expected
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
你更新到最新版试试啊 这个应该7月份就修了

**Comment by t8c** [comment]
重装试过了，仍然一样地报错
sha512值

2ae20f7444b316a3bb2b4f78b61d2d4d35ab716b48275422acb8228dcbca2f5c460183a558ae9650a91f8bf79132a8c82ca96bf63f65a4e6bf73df4bdc7c2fd7
  xware-desktop-0.13-1.git0c69374.fc22.i686.rpm

**Comment by Xinkai** [comment]
我的意思是git master的最新版

**Comment by Xinkai** [comment]
网友打包的可能会有延迟
