### ISSUE TITLE
启动出现infoPoll failed with error 

### ISSUE THREAD

**Issue by helinb** [Xinkai/XwareDesktop#213]
在archlinux下命令行运行xware-desktop每次显示
Qt[WARN] default None in None, on line 0
    PulseAudioService: pa_context_connect() failed
infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND
infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND
infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND
infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND
infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND
Vector smash protection is enabled.
infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND
Qt[WARN] default None in None, on line 0
    QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND
infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND
infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND
infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND

**Comment by Xinkai** [comment]
`infoPoll failed with error XwaredSocketError.CLIENT_SOCKET_NOT_FOUND` 正常
其它的好像就不那么正常了
