### ISSUE TITLE
启动xwared-desktop的时候，提示错误

### ISSUE THREAD

**Issue by shatian114** [Xinkai/XwareDesktop#215]
xwared desktop上演了一出悲剧,archlinux，xfce桌面

**Comment by Xinkai** [comment]
贴出报告啊

**Comment by shatian114** [comment]
发行版: Arch Linux 
桌面环境: XFCE/xfce
应用程序版本: fa3618e8119695658e98e75e8b001e1ed9dd1c22

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
TypeError: invalid result from TaskModel.roleNames(), a dict value has type 'str' but 'QByteArray' is expected
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
升级

**Comment by shatian114** [comment]
可以了，谢谢
