### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Ka-chanNi** [Xinkai/XwareDesktop#216]
补充描述计算机。
戴尔灵越

简述在什么情况下发生了这个问题。
第一次启动时

======================== 报告 ========================
错误发生在MainThread
```
TypeError: invalid result from TaskModel.roleNames(), a dict value has type 'str' but 'QByteArray' is expected
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
版本太低了 用git master编译
