### ISSUE TITLE
fedora 22 x64 mate desktop can't lanuch

### ISSUE THREAD

**Issue by chenyudev** [Xinkai/XwareDesktop#219]
======================== 报告 ========================
错误发生在MainThread
```
TypeError: invalid result from TaskModel.roleNames(), a dict value has type 'str' but 'QByteArray' is expected
```
======================== 结束 ========================

**Comment by chenyudev** [comment]
发行版: Fedora 22 (Twenty Two) 22
桌面环境: MATE/mate
应用程序版本: 开发版

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
TypeError: invalid result from TaskModel.roleNames(), a dict value has type 'str' but 'QByteArray' is expected
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
升级就好

**Comment by infinite2009** [comment]
不知道我的经验能不能帮助你：我是用root账号make && make install安装的，这里有个fedora22的问题是，make过程中要include很多/usr/include/python2.7里边的头文件，但是make代码是去/usr/include/里边找的，所以make会失败，解决方法是把/usr/include/python2.7里边的头文件复制到/usr/include里边，或者用shell脚本批量做软链接过去，然后就可以顺利make和make install，可以启动了

**Comment by Xinkai** [comment]
这个问题和python什么的没关系

**Comment by Xinkai** [comment]
你那个用python2.7的方法解决的什么问题，我不清楚，但肯定是旁门左道的办法。。根本没用py2
