### ISSUE TITLE
fedora

### ISSUE THREAD

**Issue by xiaode-c** [Xinkai/XwareDesktop#221]
发行版: Fedora 22 (Twenty Two) 22
桌面环境: GNOME-Classic:GNOME/gnome-classic
应用程序版本: 开发版

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
TypeError: invalid result from TaskModel.roleNames(), a dict value has type 'str' but 'QByteArray' is expected
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
升git master
