### ISSUE TITLE
ubuntu14.04下error

### ISSUE THREAD

**Issue by zheteng123** [Xinkai/XwareDesktop#223]
发行版: Ubuntu 14.04.3 LTS 14.04
桌面环境: Unity/ubuntu
应用程序版本: 823f232dbd6f64fadc42388ccb8bb3bad4404046

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 85, in __init__
    from Widgets.systray import Systray
  File "/opt/xware-desktop/frontend/Widgets/__init__.py", line 15, in <module>
    from ._KdeSystemTrayIcon import KdeSystemTrayIcon as CompatSystemTrayIcon
  File "/opt/xware-desktop/frontend/Widgets/_KdeSystemTrayIcon.py", line 12, in <module>
    from Extensions.DBusTypes import DBusTypes
ImportError: libDBusTypes.so.1: cannot open shared object file: No such file or directory
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
一装上就有这个问题么？
还是变出这个问题了？

**Comment by zheteng123** [comment]
反应好快，先点赞！
再说一上面的问题，是直接安装的deb包出的问题。
后来根据您github的编译安装的方法，刚刚安装成功了，赞！

正在尝试下载人人的美剧，但流量一直为0，不知道是不是公司限了，再试试其他再跟您反馈。

再次多谢！！！

**Comment by zheteng123** [comment]
刚试了ed2k链接是可以新建成功，流量0K。
磁力链接卡在了创建任务那儿没反应了

**Comment by zheteng123** [comment]
貌似磁力是不能创建任务，一直“正在创建任务……”，只能点取消

**Comment by Xinkai** [comment]
磁力链接解析一直有问题的。。。
迅雷的二进制里这功能弱得要死，跟Windows上的迅雷根本不能比。
磁力解析好像是依赖他们服务器的缓存的，姑且叫做“云解析”吧。

在他们服务器解析完成磁力链之前，是没办法的。

**Comment by zheteng123** [comment]
嗯，试用了，有些下载速度确实不错，有些就慢，应该是跟源有关系。还是挺好用的！

另外，麻烦请教个问题，这个NAS的可用空间是什么意思？我这默认是100GB，下载多了后，空间会不会不够用了？如何扩展？

**Comment by zheteng123** [comment]
这个空间，是不是指自己的磁盘可用空间啊？猛然好像感觉是这么个意思了

**Comment by Xinkai** [comment]
可用空间显示的不准。。这是这个项目的已知问题，不是迅雷本身的
请以挂载文件夹所在分区的剩余大小为准

**Comment by zheteng123** [comment]
哦，好的，多谢
