### ISSUE TITLE
在fedora22中启动失败

### ISSUE THREAD

**Issue by infinite2009** [Xinkai/XwareDesktop#225]
用的是FZUG源的，完后直接用命令行启动，然后得到如下提示：
发行版: Fedora 22 (Twenty Two) 22
桌面环境: X-Cinnamon/cinnamon
应用程序版本: 开发版

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
TypeError: invalid result from TaskModel.roleNames(), a dict value has type 'str' but 'QByteArray' is expected
```
======================== 结束 ========================

**Comment by infinite2009** [comment]
补充下，系统默认的python版本是2.7.10，不知道是不是这个问题

**Comment by infinite2009** [comment]
[luodongyang@infinite2009-pc ~]$ python3 /usr/share/xware-desktop/frontend/launcher.py 
TypeError: invalid result from TaskModel.roleNames(), a dict value has type 'str' but 'QByteArray' is expected
Fatal Python error: PyImport_GetModuleDict: no module dictionary!

Current thread 0x00007fdaee982700 (most recent call first):
  File "/usr/share/xware-desktop/frontend/models/ProxyModel.py", line 50 in setSourceModel
  File "/usr/share/xware-desktop/frontend/launcher.py", line 75 in __init__
  File "/usr/share/xware-desktop/frontend/launcher.py", line 282 in <module>

**Comment by Xinkai** [comment]
升级到Git master
