### ISSUE TITLE
fedora23 缺少一个qt库

### ISSUE THREAD

**Issue by jimmy9065** [Xinkai/XwareDesktop#232]
qt5-webkit需要引用qt5-sensors
FZUG的安装包并没有加入这个依赖项，需要手动安装

**Comment by Xinkai** [comment]
谢谢报告。
不过还是希望打包者能够了解这一情况

**Comment by jimmy9065** [comment]
抱歉，以为你们是一起的呢。。。我去那里报告

**Comment by 1dot75cm** [comment]
see https://github.com/FZUG/repo/issues/41
