### ISSUE TITLE
无法解析迅雷链接

### ISSUE THREAD

**Issue by blaueck** [Xinkai/XwareDesktop#234]
有一两周没用到xware-desktop了，这两天用，发现无法解析迅雷链接。我的发行版是archlinux，已经尝试更新过软件了。在输入迅雷下载链接的时候，界面一直提示说在解析中，但是没其他反应，也无法点击开始按钮, 终端也没有报错信息。但是其他协议的链接是可以正常下载的。用转换链接的软件，将原来的迅雷链接转换成ed2k的链接，可以正常解析并且下载。因为xware-desktop会自动把剪贴板的迅雷链接转成ed2k，所以还可以继续使用。

**Comment by Xinkai** [comment]
那个剪贴板监听和特殊链接解析的功能是我自己做的，所以不会受到网络影响。
估计你不能用了，就是因为迅雷服务器日了。可能会自己好，可能不会……
