### ISSUE TITLE
unity状态栏双图标。

### ISSUE THREAD

**Issue by KoutenXiu** [Xinkai/XwareDesktop#235]
![2015-11-09 19-46-28](https://cloud.githubusercontent.com/assets/15728562/11032980/b697ffd8-871a-11e5-9920-30ee14d0c350.png)
RT&T
如题和图
系统是ub15.10，没有报错，嘛，意义不大的小问题。
（虽然足够逼死强迫症）

**Comment by KoutenXiu** [comment]
仔细看看居然发现这两只鸟长得还不一样诶！

**Comment by KoutenXiu** [comment]
刚才排查了一下，两个都是/hicolor/scalable/apps下的xware-desktop.svg。不一样只是个错觉，把这张图删了，状态栏就没图标了，不会出现有两个图标的情况。

**Comment by Xinkai** [comment]
。。。什么神奇的bug都有
