### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Rubs-rough** [Xinkai/XwareDesktop#240]
发行版: Debian GNU/Linux 8 (jessie) 8
桌面环境: GNOME/default
应用程序版本: 2baa049c2f7ed0060cb6eeb858e432aa3f7d862d

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在MainThread
```
Traceback (most recent call last):
  File "/usr/bin/xware-desktop", line 282, in <module>
    app = XwareDesktop(sys.argv)
  File "/usr/bin/xware-desktop", line 86, in __init__
    from Notify import Notifier
  File "/opt/xware-desktop/frontend/Notify/__init__.py", line 7, in <module>
    from ._DBusNotifier import Notifier
  File "/opt/xware-desktop/frontend/Notify/_DBusNotifier.py", line 8, in <module>
    from PyQt5.QtMultimedia import QSound
ImportError: No module named 'PyQt5.QtMultimedia'
```
======================== 结束 ========================

**Comment by Xinkai** [comment]
请使用debian包安装 不要make make install

**Comment by Rubs-rough** [comment]
我git了一份然后dpkg-buildpackage  dpkg -i 但在debian8.2就会出现这个bug  
作者可否分享一份amd64的.deb包，附邮箱 13011133266@163.com  跪求

**Comment by Rubs-rough** [comment]
我git了一份然后dpkg-buildpackage  dpkg -i 但在debian8.2就会出现这个bug  
作者可否分享一份amd64的.deb包，附邮箱 13011133266@163.com  跪求
