### ISSUE TITLE
安装后收不到激活设备邀请码，有啥办法吗？

### ISSUE THREAD

**Issue by sany98215** [Xinkai/XwareDesktop#254]
安装后收不到激活设备邀请码，有啥办法吗？

**Comment by pocmon** [comment]
系统重启没？

在 2015年12月31日 21:02, sany98215 写道:

**Comment by sany98215** [comment]
修改了自启动方式后重启就收到了，能注册设备。多谢！
不过我遇到了新问题，添加bt任务，卡在创建任务界面，无法继续
