### ISSUE TITLE
能不能单独抽出一个核心做成命令行工具

### ISSUE THREAD

**Issue by zhout26** [Xinkai/XwareDesktop#265]
这个软件能不能单独抽出一个核心，做成命令行工具，我的服务器没有x桌面。

**Comment by Xinkai** [comment]
我现在已经基本不管这个项目了。
本地接口我都整理在这里。`src/frontend/libxware/vanilla.py` 。你自己去写个简单的脚本就可以了。

不过这里面的接口Bug非常多。所以不好用很正常

**Comment by gccpacman** [comment]
@zhout26 装个vnc server，或者ssh的X11_forward模式？ 登陆过一次以后应该就不用管了吧
