### ISSUE TITLE
迅雷卡在【创建新任务】

### ISSUE THREAD

**Issue by cloudwalkerfre** [Xinkai/XwareDesktop#277]
BT链接创建新任务后，点击开始下载，一直卡在【正在创建新任务...】不动

迅雷版本：0.13-3.gitb77d20b.fc23
Fedora：Linux version 4.3.5-300.fc23.x86_64

**Comment by Xinkai** [comment]
本项目不再维护

**Comment by petronny** [comment]
虽然不再维护了，但是这个issue还是没有解决。请reopen这个issue，让别人来解决

**Comment by Xinkai** [comment]
一般这种是迅雷的WebUI的问题。你要是实在想用，可以登陆yuancheng.xunlei.com操作

**Comment by Xinkai** [comment]
除了迅雷员工这种问题不好办的
