### ISSUE TITLE
弃坑是什么意思？

### ISSUE THREAD

**Issue by sonichy** [Xinkai/XwareDesktop#292]
uget无法下载emule，摸到这里，看见了大大的弃坑2个字，不懂，搜索一番，原来是放弃开发的意思......
安装完后，页面显示添加设备，无法添加新任务，左下角3个感叹号，无法挂载，重启Deepin系统后正常下载了。
这么好的项目，你弃坑，太可惜了。
Linux找个下载工具有多难，虽然核心不再更新，但是仍然可用，挂载方法不好用，希望能够直接选择下载目录，button、spin控件不知为何也被压扁，所以软件仍然有可以改进的地方。
你看人家7-zip，几年不更新，但是不弃坑。
做Linux平台最好用的下载软件，绝不放弃，直至核心的终结。

**Comment by alick** [comment]
#273 作者说的很清楚了
